Beanstalk/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

api/urls.py
from rest_framework import routers
from .views import UserViewSet, NonLoginUserViewSet, CartUserViewSet, OrderViewSet, CategoryViewSet, AllergyViewSet, MenuViewSet


router = routers.DefaultRouter()
router.register(r'user', UserViewSet)
router.register(r'non_login_user', NonLoginUserViewSet)
router.register(r'cart', CartUserViewSet)
router.register(r'order', OrderViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'allergy', AllergyViewSet)
router.register(r'menu', MenuViewSet)

beanstalk/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gaestd_py_django_local_static]
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include
from api.urls import router as api_router
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('customer.urls')),
    path('', include('restaurant.urls')),
    url(r'^api/', include(api_router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# [END gaestd_py_django_local_static]

customer/urls.py
from django.urls import path
from . import views


app_name = 'customer'
urlpatterns = [
    path('', views.index, name='index'),
    path('table/', views.table, name='table'),
    path('waiting/', views.waiting, name='waiting'),
    path('waiting/admin/', views.waiting_admin, name='waiting_admin'),
    path('judge/', views.judge, name='judge'),
    path('allowing/', views.allowing, name='allowing'),
    path('deny/', views.deny, name='deny'),
    path('denied/', views.denied, name='denied'),
    path('menu/', views.menu, name='menu'),
    path('<int:category_id>/filter/', views.filter, name='filter'),
    path('<int:menu_id>/detail/', views.menu_detail, name='menu_detail'),
    # path('<int:menu_id>/detail/request/', views.request, name='request'),
    # path('<int:menu_id>/detail/request/delete/', views.request_del, name='request_del'),
    # path('<int:cart_id>/detail/cart/request/', views.request_cart, name='request_cart'),
    # path('<int:cart_id>/detail/cart/request/delete/', views.request_cart_del, name='request_cart_del'),
    path('cart/<int:menu_id>/', views.cart, name='cart'),
    path('cart/static/', views.cart_static, name='cart_static'),
    path('cart/<int:menu_id>/detail/', views.cart_detail, name='cart_detail'),
    path('cart/<int:cart_id>/cart_ch/', views.cart_ch, name='cart_ch'),
    path('order/', views.order, name='order'),
    path('nomiho/<int:nomiho_id>', views.nomiho, name='nomiho'),
    path('history/', views.history, name='history'),
    path('thanks/', views.thanks, name='thanks'),
    path('stop/', views.stop, name='stop'),
]

customer/models.py
from customer.views import table
from django.db import models
from django.db.models.base import Model
from account.models import nonLoginUser
from restaurant.models import Option, Menu, Nomiho


# Create your models here.
class Cart(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.PROTECT, blank=True, null=True)
    num = models.PositiveIntegerField("個数", blank=True, null=True)
    option = models.ManyToManyField(Option, blank=True, null=True)
    request = models.TextField("リクエスト", max_length=500, blank=True, null=True)
    customer = models.ForeignKey(nonLoginUser, on_delete=models.PROTECT, blank=True, null=True)
    curr = models.BooleanField("今回分か否か", default=False, blank=True, null=True)
    created_at = models.DateTimeField("カート追加時刻", auto_now=True)

    def __str__(self):
        return str(self.menu)


class Order(models.Model):
    status = models.CharField("ステータス", max_length=256, blank=True, null=True)
    menu = models.ForeignKey(Menu, on_delete=models.PROTECT, blank=True, null=True)
    num = models.PositiveIntegerField("個数", blank=True, null=True)
    option = models.ManyToManyField(Option, blank=True, null=True)
    request = models.TextField("リクエスト", max_length=500, blank=True, null=True)
    customer = models.ForeignKey(nonLoginUser, on_delete=models.PROTECT, blank=True, null=True)
    curr = models.BooleanField("今回分か否か", default=False, blank=True, null=True)
    created_at = models.DateTimeField("オーダー発生時刻", auto_now=True)

    def __str__(self):
        return str(self.status)


class NomihoOrder(models.Model):
    status = models.CharField("ステータス", max_length=256, blank=True, null=True)
    nomiho = models.ForeignKey(Nomiho, on_delete=models.DO_NOTHING, blank=True, null=True)
    table = models.PositiveIntegerField("テーブル番号", blank=True, null=True)
    num = models.PositiveIntegerField("人数", blank=True, null=True)
    customer = models.ForeignKey(nonLoginUser, on_delete=models.DO_NOTHING, blank=True, null=True)
    curr = models.BooleanField("今回分か否か", default=False, blank=True, null=True)
    created_at = models.DateTimeField("飲み放題開始時刻", auto_now=True)

    def __str__(self):
        return str(self.status)

customer/views.py
from typing import KeysView
from restaurant.views import order_status_ch, send_code
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q, Sum
from django.shortcuts import resolve_url
from itertools import chain
import time
import requests
import customer.models
from .function import (
    permission,
    judging,
    expired,
    make_session
)
from account.models import Table, User, nonLoginUser
from restaurant.models import Allergy, Category, Menu, Nomiho
from beanstalk.settings import (
    DEBUG,
    ONE_SIGNAL_APP_ID,
    ONE_SIGNAL_REST_API_KEY
)


# Create your views here.
def stop_nomiho(request, duration):
    uuid = request.session['nonloginuser_uuid']
    user_uuid = nonLoginUser.objects.get(uuid=uuid)

    # TODO: sleepだと止まる
    time.sleep(int(duration)*60)
    user_uuid.nomiho = False
    user_uuid.save()


def index(request):
    return render(request, 'customer/index.html')


def table(request):
    user = request.user

    # 新規/既存をセッションで判断する
    # 新規
    try:
        if not 'nonloginuser_uuid' in request.session:

            if user.is_authenticated:
                request.session.flush()
                return redirect('restaurant:logout')
            else:
                return render(request, 'customer/table.html')
        # 既存
        else:
            return redirect('customer:menu')
    except Exception:
        return redirect('customer:thanks')


def waiting_admin(request):

    expired(request)

    try:
        uuid = request.session['nonloginuser_uuid']
        user_uuid = nonLoginUser.objects.get(uuid=uuid)

        if user_uuid.allowed == 'pre_admin':
            return render(request, 'customer/waiting_admin.html')
        else:
            return redirect('customer:menu')

    except Exception:
        return redirect('customer:thanks')


def waiting(request):

    expired(request)

    try:
        uuid = request.session['nonloginuser_uuid']
        user_uuid = nonLoginUser.objects.get(uuid=uuid)

        if user_uuid.allowed == 'denied':
            return redirect('customer:denied')
        elif user_uuid.allowed == 'allowed':
            messages.info(request, f'承認されました')
            return redirect('customer:menu')
        elif user_uuid.allowed == 'unknown':
            return render(request, 'customer/waiting.html')

    except Exception:
        return redirect('customer:thanks')


def judge(request):
    return render(request, 'customer/judge.html')


def allowing(request):

    user = request.user
    if not user.is_authenticated:

        expired(request)

        try:
            uuid = request.session['nonloginuser_uuid']
            user_uuid = nonLoginUser.objects.get(uuid=uuid)
            permission(user_uuid)

            # unknownが一人以上いたら、その人たちをallowedにする
            table_num = request.session['table']
            unknown_user_list = nonLoginUser.objects.defer(
                'created_at').filter(allowed='unknown', table=table_num, active=True)

            if unknown_user_list.count() > 0:
                for unknown_user in unknown_user_list:
                    unknown_user.allowed = 'allowed'
                    unknown_user.save()

        except Exception:
            return redirect('customer:thanks')

    return redirect('customer:menu')


def deny(request):

    expired(request)

    try:
        uuid = request.session['nonloginuser_uuid']
        user_uuid = nonLoginUser.objects.get(uuid=uuid)
        permission(user_uuid)

        # unknownが一人以上いたら、その人たちをdeniedにする
        table_num = request.session['table']

        unknown_user_list = nonLoginUser.objects.defer(
            'created_at').filter(allowed='unknown', table=table_num, active=True)

        if unknown_user_list.count() > 0:
            for unknown_user in unknown_user_list:
                unknown_user.allowed = 'denied'
                unknown_user.save()

        return redirect('customer:menu')

    except Exception:
        return redirect('customer:thanks')


def denied(request):
    return render(request, 'customer/denied.html')


def menu(request):
    user = request.user

    categories = Category.objects.defer('created_at').order_by('id')
    allergies = Allergy.objects.defer('created_at').order_by('id')

    restaurant_name = None
    restaurant_logo = None
    user_uuid = None
    same_num = None
    nomiho_is_started = False

    # NOTE: static
    # from here
    try:
        restaurant = User.objects.get(id=1)
    except Exception:
        pass
    try:
        restaurant = User.objects.get(id=2)
    except Exception:
        pass
    try:
        restaurant = User.objects.get(id=3)
    except Exception:
        pass
    # to here

    try:
        restaurant_name = restaurant.name
        restaurant_logo = restaurant.logo.url
    except Exception:
        pass

    if user.is_authenticated:
        table_num = '管理者'
    else:

        # 新規の客かどうかをセッションで判断する
        try:
            # 新規
            if not 'nonloginuser_uuid' in request.session:
                table_num = request.GET.get('table')
                if table_num == 0 or None:
                    return redirect('customer:thanks')

                # 店側から承認を得る1人目のテーブルユーザー（adminユーザー）か、1人目のテーブルユーザーからの承認を得るユーザーかの分岐点
                # 現在のテーブルで最初の1人目の場合
                if nonLoginUser.objects.defer('created_at').filter(table=table_num, active=True).count() == 0:
                    newtable = Table(table=table_num, active=True)
                    newtable.save()

                    # 開発する時は不便なのでadminにしてしまう
                    # if DEBUG:
                    #     newuser = nonLoginUser(
                    #         allowed="admin", table=table_num, active=True)
                    # else:
                    #     newuser = nonLoginUser(
                    #         allowed="pre_admin", table=table_num, active=True)

                    newuser = nonLoginUser(table=table_num, active=True)
                    newuser.save()

                    uuid = str(newuser.uuid)
                    user_uuid = newuser

                    make_session(request, restaurant_name,
                                 restaurant_logo, table_num, uuid)

                    # return redirect('customer:waiting_admin')
                # 現在のテーブルで最初の1人がすでにいる場合
                else:
                    # 店側側から承認前の1人目以上の客がいる場合
                    # if nonLoginUser.objects.defer('created_at').filter(allowed="pre_admin", table=table_num, active=True).count() > 0:
                    #     newuser = nonLoginUser(
                    #         allowed="pre_admin", table=table_num, active=True)

                    # # 1人目の客が店からすでに承認を得ている場合
                    # else:
                    newuser = nonLoginUser(table=table_num, active=True)

                    newuser.save()

                    same_table = Table.objects.get(
                        table=table_num, active=True)
                    same_table.user += 1
                    same_table.save()

                    uuid = str(newuser.uuid)
                    user_uuid = newuser

                    make_session(request, restaurant_name,
                                restaurant_logo, table_num, uuid)

                    # return redirect('customer:waiting_admin')

            # 既存
            else:
                user_uuid = permission(request)
                # unknownを検知したらallow.htmlに遷移させる
                table_num = judging(request)

                same_user_table = nonLoginUser.objects.defer(
                    'created_at').filter(table=table_num, active=True)

                same_num = same_user_table.count()

                # 後からやってきた客よりも先に飲み放題を開始していた場合、
                # 後から来た客のメニューにも飲み放題開始ボタンを表示させないようにする
                # 兼メニューを選択できるようにする
                same_user_table_list = nonLoginUser.objects.defer(
                    'created_at').filter(table=table_num, active=True, nomiho=True)

                same_table_num = same_user_table_list.count()

                if same_table_num != 0:
                    user_uuid.nomiho = True
                    user_uuid.save()

                    nomiho_is_started = True

        except Exception:
            return redirect('customer:thanks')

    try:
        if 'category_name' in request.session:
            category = request.session['category_name']

        # カテゴリーセッションがない場合（つまり一番最初に訪れた時）は、一番最初のカテゴリーのページとする
        else:

            try:
                category = categories[0].id
            except Exception:
                category = None

            # カテゴリーIDのセッションを作成
            request.session['category_name'] = category

    except Exception:
        return redirect('customer:thanks')

    if category != None:
        menus = Menu.objects.defer('chef_img', 'comment', 'created_at').filter(
            category=category).order_by('-id')
    else:
        menus = Menu.objects.defer(
            'chef_img', 'comment', 'created_at').order_by('-id')

    ctx = {
        'categories': categories,
        'menus': menus,
        'allergies': allergies,
        'user_uuid': user_uuid,
        'same_num': same_num,
        'nomiho_is_started': nomiho_is_started,
    }

    return render(request, 'customer/menu.html', ctx)


def filter(request, category_id):
    user = request.user
    same_num = None
    nomiho_is_started = False

    if not user.is_authenticated:
        expired(request)

    try:
        category_id = Category.objects.get(id=category_id)

        # カテゴリーのセッションを更新
        request.session['category_name'] = category_id.id
        menus = Menu.objects.defer('chef_img', 'comment', 'created_at').filter(
            category=category_id).order_by('-id')
    except Exception:
        menus = None

    try:
        user_uuid = permission(request)
        table_num = judging(request)

templates/customer/base__next.html
{% extends 'base.html' %}
{% load static %}

{% block custom__header %}
  <title>オンラインメニュー</title>
{% endblock %}

{% block content %}
<div class="wrapper w-100">
  <div class="inner__wrapper m-auto">
    <div class="board board__customer shadow beautify text-center pb-5">
      {% include 'components/customer/header.html' %}

      {% block inner__content %}
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

templates/customer/cart.html
{% extends 'customer/base__next.html' %}
{% load static %}
{% load humanize %}

{% block custom__header %}
  <title>注文予定</title>
{% endblock %}

{% block inner__content %}
<section class="menu-list">
  <div class="d-flex flex-wrap">
    {% for cart in carts %}
      <form class="el__pointer mx-auto my-1 menu-item shadow" action="{% url 'customer:cart_detail' cart.menu.id %}" method="GET">
        <button type="submit" class="w-100 h-100 p-0 focus" onclick="loading_show()">
          <img class="lazyload" data-src="{{ cart.menu.img.url }}" alt="Menu">
          <div class="text-box">
            <p class="text-left pl-2">{{ cart.menu.name }}</p>
            {% if not cart.menu.category.nomiho == True %}
              <p class="text-right pr-2">¥ {{ cart.menu.price | intcomma }}</p>
            {% endif %}
          </div>
          <p class="pt-1 cart-num icon icon__red text__bold">{{ cart.num }}</p>
          {% if cart.request %}
            <button type="button" class="btn cart-request btn__orange shadow px-3" data-toggle="modal" data-target="#request-cart-btn-{{ cart.id }}__ModalCenter">
              <i class="fas fa-pencil-alt"></i>
            </button>
            {% include 'components/customer/modal/request_cart.html' %}
          {% endif %}
          <!-- hidden -->
          <input type="hidden" name="num" value="{{ cart.num }}">
          <input type="hidden" name="id" value="{{ cart.id }}">
          <input type="hidden" name="type" value="cart">
        </button>
      </form>
    {% endfor %}
  </div>

  {% if not user.is_authenticated %}
    {% include 'components/customer/modal/order.html' %}
  {% endif %}
</section>
{% endblock %}

templates/customer/cart_detail.html
{% extends 'customer/base__next.html' %}
{% load static %}
{% load humanize %}

{% block inner__content %}
<section class="menu-detail">
  {% include 'components/customer/menu_detail.html' %}

    {% if not user.is_authenticated %}
      {% if not tag == 'off' %}
        <div class="btn__fixed-wider ml-5 pl-5">
          <form class="cart-form mb-4" action="{% url 'customer:cart_ch' cart_id %}" method="GET">
            <div class="d-flex input__fixed justify-content-center align-items-center">
              <p class="text__bold plus-minus el__pointer" id="cartMinus">-</p>
              <input type="number" name="cart_num" class="ml-4 mr-2 text__bold" value="{{ num }}" id="cartNum" required readonly>
              <p class="pt-2 text__bold text__large">個</p>
              <p class="ml-4 text__bold plus-minus el__pointer" id="cartPlus">+</p>
            </div>
            <!-- hidden -->
            <input type="hidden" name="type" value="change">
            <button type="submit" class="px-5 btn btn__blue shadow" onclick="loading_show(); style.display='none';">
              注文する個数の変更
            </button>
          </form>

          <form class="cart-form" action="{% url 'customer:cart_ch' cart_id %}" method="GET">
            <!-- hidden -->
            <input type="hidden" name="type" value="delete">
            <button type="submit" class="btn btn__grey shadow" onclick="loading_show(); style.display='none';">
              注文予定からキャンセル
            </button>
          </form>
        </div>
      {% endif %}
    {% endif %}
  </div>
</section>
{% endblock %}

templates/customer/denied.html
{% extends 'customer/base__next.html' %}
{% load static %}

{% block custom__header %}
  <title>拒否されました</title>
{% endblock %}

{% block content %}
<section class="w-100 waiting">
  <div class="img">
    <img src="{% static 'img/top-view.jpg' %}" alt="Top View">
  </div>
  <div class="forms text-center title">
    <h3 class="pb-5 mb-5">拒否されました</h3>
    <p>*テーブルにご自身のみいらっしゃる状態でこの画面が表示されましたら、<br>お手数ですが店員をお呼びください。</p>
  </div>
</section>
{% endblock %}

templates/customer/history.html
{% extends 'customer/base__next.html' %}
{% load static %}
{% load humanize %}

{% block custom__header %}
  <title>注文履歴</title>
{% endblock %}

{% block inner__content %}
<section class="menu-list">
  <div class="d-flex flex-wrap">
    {% for cart in carts %}
      <form class="el__pointer mx-auto my-1 menu-item shadow" action="{% url 'customer:cart_detail' cart.menu.id %}" method="GET">
        <button type="submit" class="w-100 h-100 p-0 focus" onclick="loading_show()">
          <img class="lazyload" data-src="{{ cart.menu.img.url }}" alt="Menu">
          <div class="text-box">
            <p class="text-left pl-2">{{ cart.menu.name }}</p>
            {% if not cart.menu.category.nomiho == True %}
              <p class="text-right pr-2">¥ {{ cart.menu.price | intcomma }}</p>
            {% endif %}
          </div>
          <p class="pt-1 cart-num icon icon__red text__bold">{{ cart.num }}</p>
          <p class="py-2 px-3 badge badge__orange">注文予定</p>
          {% if cart.request %}
            <button type="button" class="btn cart-request btn__orange shadow px-3" data-toggle="modal" data-target="#request-cart-btn-{{ cart.id }}__ModalCenter">
              <i class="fas fa-pencil-alt"></i>
            </button>
            {% include 'components/customer/modal/request_cart.html' %}
          {% endif %}
          <!-- hidden -->
          <input type="hidden" name="num" value="{{ cart.num }}">
          <input type="hidden" name="id" value="{{ cart.id }}">
          <input type="hidden" name="type" value="history-cart">
        </button>
      </form>
    {% endfor %}

    {% for order in orders %}
      <form class="el__pointer mx-auto my-1 menu-item shadow" action="{% url 'customer:cart_detail' order.menu.id %}" method="GET">
        <button type="submit" class="w-100 h-100 p-0 focus" onclick="loading_show()">
          <img class="lazyload" data-src="{{ order.menu.img.url }}" alt="Menu">
          <div class="text-box">
            <p class="text-left pl-2">{{ order.menu.name }}</p>
            {% if not order.menu.category.nomiho == True %}
              <p class="text-right pr-2">¥ {{ order.menu.price | intcomma }}</p>
            {% endif %}
          </div>
          <p class="pt-1 cart-num icon icon__red text__bold">{{ order.num }}</p>
          {% if order.status == '調理中' %}
            <p class="py-2 px-3 badge badge__turquoise">調理中</p>
            <!-- hidden -->
            <input type="hidden" name="order_status" value="調理中">
          {% elif order.status == 'キャンセル' %}
            <p class="py-2 px-3 badge badge__blue">キャンセル</p>
            <!-- hidden -->
            <input type="hidden" name="order_status" value="キャンセル">
          {% elif order.status == '済' %}
            <p class="py-2 px-3 badge badge__grey">ご提供済</p>
            <!-- hidden -->
            <input type="hidden" name="order_status" value="済">
          {% endif %}
          <input type="hidden" name="num" value="{{ order.num }}">
          <input type="hidden" name="id" value="{{ order.id }}">
          <input type="hidden" name="type" value="history-order">
        </button>
      </form>
    {% endfor %}
  </div>

  <hr/>
  <div class="row">
    <div class="col-6">
      <p class="py-2 px-3 badge badge__orange shadow mb-3">注文予定</p>
      <p>¥ {{ request.session.orders_in_cart | intcomma }}</p>
    </div>
    <div class="col-6">
      <p class="py-2 px-3 badge badge__grey shadow mb-3">注文済</p>
      {% if orders_in_order %}
        <p>¥ {{ orders_in_order | intcomma }}</p>
      {% else %}
        <p>¥ 0</p>
      {% endif %}
      {% if user_uuid.nomiho_price != 0 %}
        <p class="pt-2">（内 {{ user_uuid.nomiho_name }} ¥ {{ user_uuid.nomiho_price | intcomma }}）</p>
      {% endif %}
    </div>
    <!-- <div class="col-4">
      <p class="py-2 px-3 badge badge__yellow shadow mb-3">合計</p>
      <p class="text__bold text_large">
        {% if request.session.total_price %}
          ¥ {{ request.session.total_price | intcomma }}
        {% else %}
          ¥ 0
      </p>
      {% endif %}
    </div> -->

    <div class="btn__fixed-wider d-flex justify-content-between">
      {% if carts %}
        <button class="btn btn__red shadow w-50 text__bold" data-toggle="modal" data-target="#order-btn__ModalCenter">
      {% else %}
        <button class="btn btn__grey shadow w-50 text__bold" disabled>
      {% endif %}
          注文
        </button>
      <form action="{% url 'customer:stop' %}" class="d-flex" method="GET">
        <button type="submit" class="btn btn__blue shadow text__bold px-sm-4 py-sm-0 py-2" id="orderStopConfirm">
          伝票表示
        </button>
      </form>
    </div>

    {% include 'components/customer/modal/order_history.html' %}
</section>
{% endblock %}

templates/customer/index.html
{% extends 'customer/base__next.html' %}
{% load static %}

{% block custom__header %}
  <title>メニュー表</title>
  <meta name="description" content="スマホからお店で簡単にメニューを注文できます">
{% endblock %}

{% block content %}
<section class="w-100 top-view">
  <div class="img">
    <img src="{% static 'img/top-view.jpg' %}" alt="Top View">
  </div>
  <div class="forms">
    <div style="visibility: hidden;">________________________________</div>
    <form class="px-auto my-5 py-5" method="GET" action="{% url 'customer:table' %}">
      <button type="submit" class="btn__glass w-100 btn shadow mb-5 text__bold text__large" onclick="loading_show()">
        タップ
      </button>
    </form>
  </div>
</section>
{% endblock %}

templates/customer/judge.html
{% extends 'customer/base__next.html' %}
{% load static %}

{% block content %}
<section class="w-100 judge">
  <div class="img">
    <img src="{% static 'img/top-view.jpg' %}" alt="Top View">
  </div>
  <div class="forms text-center title">
    <h3 class="pb-5 mb-5">同テーブルに承認待ちの方がいます</h3>
    <div class="d-flex justify-content-around align-items-center">
      <form action="{% url 'customer:allowing' %}" method="GET">
        <button type="submit" class="btn__glass w-100 btn shadow mb-5 text__bold text__large" onclick="loading_show()">
          許可する
        </button>
      </form>
      <form action="{% url 'customer:deny' %}" method="GET">
        <button type="submit" class="btn__glass w-100 btn shadow mb-5 text__bold text__large" onclick="loading_show()">
          拒否
        </button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

templates/customer/menu.html
{% extends 'customer/base__next.html' %}
{% load static %}
{% load humanize %}

{% block inner__content %}
<section class="menu-list">
  <div class="category mb-3">
    <div class="d-flex flex-wrap category-wrapper">
      {% for category in categories %}
        <form action="{% url 'customer:filter' category.id %}" method="GET">
          {% if category.id == request.session.category_name %}
            <button type="submit" class="category-btn focus focused p-2 text__bold" name="category" value="{{ category }}" onclick="loading_show()">
          {% else %}
            <button type="submit" class="category-btn focus p-2 text__bold" name="category" value="{{ category }}" onclick="loading_show()">
          {% endif %}
              {{ category.name }}
            </button>
        </form>
      {% endfor %}
    </div>

    {% include 'components/restaurant/modal/category.html' %}
  </div>

  <!-- 飲み放題プランの表示箇所 -->
  <section class="nomiho">
    <!-- もしそもそも飲み放題プランがある場合 -->
    {% include 'components/customer/modal/nomiho.html' %}
  　
    {% if user.is_authenticated and nomiho_category == 'Yes' %}
      <div>
        {% include 'components/restaurant/modal/nomiho.html' %}
      </div>
    {% else %}
    {% endif %}
  </section>

  <!-- 飲み放題を開始していない場合は、選択できないようにする -->
  <!-- 飲み放題を1つでも開始した場合、全て選択できるようにする -->
  <div class="d-flex flex-wrap">
    {% for menu in menus %}
      {% if menu.category.nomiho == True and user_uuid.nomiho == False and not user.is_authenticated %}
        <form class="mx-auto my-1 menu-item shadow el__dactivate" action="{% url 'customer:menu_detail' menu.id %}" method="GET">
      {% else %}
        <form class="mx-auto my-1 menu-item shadow el__pointer" action="{% url 'customer:menu_detail' menu.id %}" method="GET">
      {% endif %}
        <button type="submit" class="w-100 h-100 p-0 focus" onclick="loading_show()">
          {% if menu.formatted_img_list %}
            <img class="m-0 lazyload" data-src="{{ menu.formatted_img.url }}" alt="Menu">
          {% endif %}
          <div class="text-box">
            <p class="text-left pl-2">{{ menu.name }}</p>
            {% if not menu.category.nomiho == True %}
              <p class="text-right pr-2">¥ {{ menu.price | intcomma }}</p>
            {% endif %}
          </div>
        </button>
      </form>
    {% endfor %}
  </div>

  {% if user.is_authenticated %}
    <div>
      {% include 'components/restaurant/modal/menu.html' %}
    </div>
  {% else %}
    <form action="{% url 'customer:cart_static' %}" method="GET">
      <button type="submit" class="btn btn__orange btn__fixed shadow" onclick="loading_show()">
        注文予定を見る
      </button>
    </form>
  {% endif %}
</section>
{% endblock %}