Beanstalk/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

api/urls.py
from rest_framework import routers
from .views import UserViewSet, NonLoginUserViewSet, CartUserViewSet, OrderViewSet, CategoryViewSet, AllergyViewSet, MenuViewSet


router = routers.DefaultRouter()
router.register(r'user', UserViewSet)
router.register(r'non_login_user', NonLoginUserViewSet)
router.register(r'cart', CartUserViewSet)
router.register(r'order', OrderViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'allergy', AllergyViewSet)
router.register(r'menu', MenuViewSet)

beanstalk/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gaestd_py_django_local_static]
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include
from api.urls import router as api_router
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('customer.urls')),
    path('', include('restaurant.urls')),
    url(r'^api/', include(api_router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# [END gaestd_py_django_local_static]

restaurant/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'restaurant'
urlpatterns = [
    path('login/', views.login_as_user, name='login'),
    # path('confirm/', views.confirm, name='confirm'),
    path('send/', views.send_code, name='send_code'),
    path('order_manage/', views.order_manage, name='order_manage'),
    path('order_manage/<int:order_id>/change/', views.order_status_ch, name='order_status_ch'),
    path('order_manage/<int:order_id>/change/menu/', views.order_status_ch_menu, name='order_status_ch_menu'),
    path('order_manage/history/', views.history, name='history'),
    path('order_manage/history/total/', views.total, name='total'),
    path('order_manage/history/total/<int:pre_admin_table>/allowing/', views.allowing, name='allowing'),
    path('order_manage/history/total/<int:pre_admin_table>/deny/', views.deny, name='deny'),
    path('order_manage/history/total/<int:active_table>/stop/', views.stop_user_order, name='stop_user_order'),
    path('order_manage/history/total/<int:active_table>/price/change/', views.price_ch, name='price_ch'),
    path('order_manage/history/daily/', views.daily, name='daily'),
    path('manage/login/', views.manage_login, name='manage_login'),
    path('manage/company/logo', views.company_logo, name='company_logo'),
    path('manage/company/name', views.company_name, name='company_name'),
    path('manage/menu/', views.manage_menu, name='manage_menu'),
    path('manage/menu/add', views.category_add, name='category_add'),
    path('manage/menu/change', views.category_ch, name='category_ch'),
    path('manage/menu/delete', views.category_del, name='category_del'),
    path('manage/menu/category/change', views.category_menu_ch, name='category_menu_ch'),
    path('manage/menu/menu/add', views.menu_add, name='menu_add'),
    path('manage/menu/menu/<int:menu_id>/delete', views.menu_del, name='menu_del'),
    path('manage/menu/menu/<int:menu_id>/img', views.menu_img_manage, name='menu_img_manage'),
    path('manage/menu/menu/<int:menu_id>/name', views.menu_name_manage, name='menu_name_manage'),
    path('manage/menu/menu/<int:menu_id>/price', views.menu_price_manage, name='menu_price_manage'),
    path('manage/menu/menu/<int:menu_id>/allergy/change', views.allergy_ch, name='allergy_ch'),
    path('manage/menu/allergy/item/add', views.allergy_add, name='allergy_add'),
    path('manage/menu/allergy/item/delete',
         views.allergy_del, name='allergy_del'),
    path('manage/menu/menu/<int:menu_id>/chef/', views.chef, name='chef'),
    path('manage/menu/nomiho/add', views.nomiho_add, name='nomiho_add'),
    path('manage/menu/nomiho/change', views.nomiho_ch, name='nomiho_ch'),
    path('manage/menu/nomiho/delete', views.nomiho_del, name='nomiho_del'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

restaurant/views.py
import datetime
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.db.models import Q
from itertools import chain
from django.template import Context, Template
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib
import datetime
from itertools import groupby
from .models import Category, Allergy, Menu, Nomiho
from account.models import Table, User, nonLoginUser
import customer.models
from beanstalk.settings import (
    CODE,
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    EMAIL_HOST,
    EMAIL_PORT
)


# Create your views here.
def login_as_user(request):
    user = User.objects.get(id=1)
    try:
        user = User.objects.get(id=2)
    except Exception:
        pass
    try:
        user = User.objects.get(id=3)
    except Exception:
        pass

    email = user.email
    ctx = {
        'email': email
    }

    return render(request, 'restaurant/login.html', ctx)


# @require_POST
# def confirm(request):
    # categories = Category.objects.defer('created_at').order_by('id')
    # try:
    #     first_category = categories[0]
    #     menus = Menu.objects.defer('created_at').filter(
    #         category=first_category).order_by('-id')
    # except:
    #     menus = None
    # allergies = Allergy.objects.all().order_by('id')
    # ctx = {
    #     'categories': categories,
    #     'menus': menus,
    #     'allergies': allergies,
    # }

#     # メールアドレスを取得
#     email = request.POST.get('username')

#     # セッションにすでにユーザがいれば削除
#     if 'user' in request.session:
#         del request.session['user']

#     # ランダムな4桁の文字列を生成
#     passcode = str(random.randrange(10)) + str(random.randrange(10)) + str(random.randrange(10)) + \
#         str(random.randrange(10))

#     # メールアドレスとパスコードのセットになったセッションを作成
#     request.session['user'] = {email: passcode}

#     # パスコードをメール送信
#     EMAIL = EMAIL_HOST_USER
#     PASSWORD = EMAIL_HOST_PASSWORD
#     TO = email

#     msg = MIMEMultipart('alternative')
#     msg['Subject'] = '【注文・メニュー管理システム】4ケタの数字をログイン画面に入力してください'
#     msg['From'] = EMAIL
#     msg['To'] = TO

#     html = """\
#     <html>
#       <head>
#       </head>
#       <body>
#         <p>{{ passcode }}</p>
#       </body>
#     </html>
#     """

#     html = Template(html)
#     context = Context({'passcode': passcode})
#     template = MIMEText(html.render(context=context), 'html')
#     msg.attach(template)

#     try:
#         s = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
#         s.starttls()
#         s.login(EMAIL, PASSWORD)
#         s.sendmail(EMAIL, TO, msg.as_string())
#         s.quit()
#         messages.info(
#             request, f"入力したメールアドレス宛てに4ケタの数字が書かれたメールを送信しました。その数字を以下に入力してください。")
#     except Exception:
#         messages.error(request, f"メール送信に失敗しました。お手数ですがメールアドレスの入力からやり直してください。")
#         return redirect('restaurant:login')

#     ctx['email'] = email

#     return render(request, 'restaurant/confirm.html', ctx)


def send_code(request):
    # メールアドレスを取得
    email = request.POST.get('username')
    code = CODE

    if email == None:
        messages.info(request, f"送信対象となるメールアドレスが登録されていません。")
        return redirect('restaurant:login')

    EMAIL = EMAIL_HOST_USER
    PASSWORD = EMAIL_HOST_PASSWORD
    TO = email

    msg = MIMEMultipart('alternative')
    msg['Subject'] = '【注文・メニュー管理システム】4ケタの暗証番号をお送りします'
    msg['From'] = EMAIL
    msg['To'] = TO

    html = """\
    <html>
      <head>
      </head>
      <body>
        <p>{{ code }}</p>
      </body>
    </html>
    """

    html = Template(html)
    context = Context({'code': code})
    template = MIMEText(html.render(context=context), 'html')
    msg.attach(template)

    try:
        s = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
        s.starttls()
        s.login(EMAIL, PASSWORD)
        s.sendmail(EMAIL, TO, msg.as_string())
        s.quit()
        messages.info(
            request, f"メールアドレス宛てに4桁の暗証番号が書かれたメールを送信しました。その数字を入力してください。")
        return redirect('restaurant:login')
    except Exception:
        messages.error(request, f"メール送信に失敗しました。お手数ですがメールアドレスが有効か、ご確認ください。")
        return redirect('restaurant:login')


def order_manage(request):
    try:
        filter_type = request.POST.get('filter-type')
    except Exception:
        filter_type = None

    # ログインから
    if request.method == 'POST' and filter_type == 'login':
        email = request.POST.get('username')
        # passcode = request.POST.get('passcode')

        # 入力されたパスコードがセッションに保持されたパスコードと一致するならログインを許可
        # if passcode == request.session['user'][email]:
        try:
            user = User.objects.get(email=email)
            code = request.POST.get('code')

            if code == CODE:
                login(request, user)
                request.session['table'] = '管理者'
            else:
                messages.info(request, f"暗証番号が異なります。")
                return redirect('restaurant:login')

        except Exception:
            messages.info(request, f"メールアドレスが異なります。")
            return redirect('restaurant:login')

        # emailのセッションを作成(いきなりオーダー画面にアクセスするお店を識別する為)
        email = user.email
        request.session['user_email'] = email

        return render(request, 'restaurant/order_manage.html')

    # いきなりこの画面から＆メニュー編集画面から戻ってくるパターン(多くの店がこの想定)
    elif 'user_email' in request.session:
        user_email = request.session['user_email']
        user = User.objects.get(email=user_email)
    else:
        user = User.objects.get(id=1)
        try:
            user = User.objects.get(id=2)
        except Exception:
            pass
        try:
            user = User.objects.get(id=3)
        except Exception:
            pass

    formatted_logo = user.formatted_logo
    name = user.name
    order_list = ''
    table = None

    active_users = nonLoginUser.objects.defer('created_at').filter(active=True)
    menus = Menu.objects.defer('created_at').order_by('id')

    # テーブル番号でフィルタした際
    if request.POST.get('table') != None:
        table = request.POST.get('table')
        active_users = nonLoginUser.objects.defer(
            'created_at').filter(table=table, active=True)

    for active_user in active_users:
        active_user_order = customer.models.Order.objects.filter(
            customer=active_user, status='調理中', curr=True).order_by('-id')
        order_list = list(chain(order_list, active_user_order))

    ctx = {
        'formatted_logo': formatted_logo,
        'name': name,
        'table': table,
        'order_list': order_list,
        'menus': menus,
    }

    return render(request, 'restaurant/order_manage.html', ctx)


@login_required
@require_POST
def order_status_ch(request, order_id):
    order_status = request.POST.get('order_status')
    order = customer.models.Order.objects.get(id=order_id)
    order.status = order_status
    order.save()

    # テーブルの合計も変更する
    if order_status == 'キャンセル':
        table_num = order.customer.table
        table = Table.objects.get(table=table_num, active=True)
        table.price -= int(order.menu.price) * int(order.num)
        table.save()

    return redirect('restaurant:order_manage')


@login_required
@require_POST
def order_status_ch_menu(request, order_id):
    required_menu_id = request.POST.get('required_menu_id')
    required_order_num = request.POST.get('required_order_num')
    menu = Menu.objects.get(id=required_menu_id)
    order = customer.models.Order.objects.get(id=order_id)

    curr_menu = order.menu
    curr_num = order.num

    order.menu = menu
    order.num = required_order_num
    order.save()

    # テーブルの合計も変更する
    table_num = order.customer.table
    table = Table.objects.get(table=table_num, active=True)
    table.price -= int(curr_menu.price) * int(curr_num)
    table.price += int(menu.price) * int(required_order_num)
    table.save()

    return redirect('restaurant:order_manage')


@login_required
def history(request):
    user = User.objects.get(id=request.user.id)
    name = user.name
    active_users = nonLoginUser.objects.defer('created_at').filter(active=True)
    menus = Menu.objects.defer('created_at').order_by('id')
    order_list = ''
    start = None
    end = None
    table = None

    # 日付の範囲指定分の売上
    if request.method == 'POST':
        filter_type = request.POST.get('filter-type')
        start = request.POST.get('start')
        end = request.POST.get('end')
        table = request.POST.get('table')

        if (start != None) and (end != None):
            request.session['filter_date_start'] = start
            request.session['filter_date_end'] = end

            if 'filter_table' in request.session:
                table = request.session['filter_table']
                same_table_users = nonLoginUser.objects.defer(
                    'created_at').filter(table=table, active=True)
            else:
                same_table_users = active_users

            if start > end:
                messages.warning(request, f"左の日付をより昔にしてください。")
                (start, end) = (end, start)

            for same_table_user in same_table_users:
                active_user_order = customer.models.Order.objects.filter(
                    customer=same_table_user, created_at__range=(start, end)).order_by('-id')
                order_list = list(chain(order_list, active_user_order))

        elif filter_type == 'date-filter-clear':
            request.session['filter_date_start'] = None
            request.session['filter_date_end'] = None

            if 'filter_table' in request.session:
                table = request.session['filter_table']
                active_users = nonLoginUser.objects.defer(
                    'created_at').filter(table=table, active=True)

            for active_user in active_users:

templates/components/restaurant/modal/allergy.html
{% if user.is_authenticated %}
  <div class="menu_allergy_handle_btn d-flex">
    <button type="button" class="px-3 shadow" data-toggle="modal" data-target="#menu-allergy-add-btn__ModalCenter">
      アレルギーそのものを<br class="d-sm-block d-none">追加
    </button>
    <button type="button" class="px-3 shadow" data-toggle="modal" data-target="#menu-allergy-del-btn__ModalCenter">
      アレルギーそのものを<br class="d-sm-block d-none">削除
    </button>
  </div>

  <div class="modal fade" id="menu-allergy-add-btn__ModalCenter" tabindex="-1" role="dialog" aria-labelledby="menu-allergy-add-btn__ModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <form class="modal-content" action="{% url 'restaurant:allergy_add' %}" method="POST">{% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="menu-allergy-add-btn__ModalCenterTitle">アレルギーそのものを追加する</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input type="text" class="text-center" name="allergy">
          <!-- hidden -->
          <input type="hidden" name="menu_id" value="{{ menu.id }}">
        </div>
        <div class="modal-footer">
          <button type="button" class="px-4 py-2 btn btn__grey" data-dismiss="modal">中止</button>
          <button type="submit" class="px-4 py-2 btn btn__orange mx-auto w-50 mx-auto" onclick="loading_show(); style.display='none';">
            実行
          </button>
        </div>
      </form>
    </div>
  </div>

  <div class="modal fade" id="menu-allergy-del-btn__ModalCenter" tabindex="-1" role="dialog" aria-labelledby="menu-allergy-del-btn__ModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <form class="modal-content" action="{% url 'restaurant:allergy_del' %}" method="POST">{% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="menu-allergy-del-btn__ModalCenterTitle">アレルギーそのものを削除する</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body d-flex justify-content-around">
          <select class="py-2 w-50" name="allergy">
            {% for allergy in allergies %}
              <option name="allergy" value="{{ allergy }}">{{ allergy }}</option>
            {% endfor %}
            <!-- hidden -->
            <input type="hidden" name="menu_id" value="{{ menu.id }}">
          </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="px-4 py-2 btn btn__grey" data-dismiss="modal">中止</button>
          <button type="submit" class="px-4 py-2 btn btn__orange mx-auto w-50 mx-auto" onclick="loading_show(); style.display='none';">
            実行
          </button>
        </div>
      </form>
    </div>
  </div>
{% endif %}

templates/components/restaurant/modal/allergy_edit.html
{% if user.is_authenticated %}
  <button type="button" class="menu-allergy-manage-btn btn btn__blue shadow px-3" data-toggle="modal" data-target="#menu-allergy-manage-btn__ModalCenter">
    <i class="fas fa-pencil-alt"></i>
  </button>

  <div class="modal fade" id="menu-allergy-manage-btn__ModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <form class="modal-content" action="{% url 'restaurant:allergy_ch' menu.id %}" method="POST">{% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">アレルギー対象の食品を編集する</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body d-flex flex-wrap align-items-center">
          {% for allergy in allergies %}
            {% if allergy in has_allergies %}
              <input class="ml-2" type="checkbox" name="allergy" value="{{ allergy }}" checked>{{ allergy }}
            {% else %}
              <input class="ml-2" type="checkbox" name="allergy" value="{{ allergy }}">{{ allergy }}
            {% endif %}
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="px-4 py-2 btn btn__grey" data-dismiss="modal">中止</button>
          <button type="submit" class="px-4 py-2 btn btn__blue w-50 mx-auto" onclick="loading_show(); style.display='none';">
            実行
          </button>
        </div>
      </form>
    </div>
  </div>
{% endif %}

templates/components/restaurant/modal/allowing.html
{% if pre_admin_table != 'None' %}
  <button class="badge__blue badge-table my-sm-0 mx-5 my-3 p-3 shadow text__bold" data-toggle="modal" data-target="#allowing-btn-{{ pre_admin_table }}__ModalCenter">
    {{ pre_admin_table }} 番
  </button>

  <div class="modal fade" id="allowing-btn-{{ pre_admin_table }}__ModalCenter" tabindex="-1" role="dialog" aria-labelledby="allowing-btn-{{ pre_admin_table }}__ModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="allowing-btn-{{ pre_admin_table }}__ModalCenterTitle">{{ pre_admin_table }}番テーブルの利用を許可しますか？</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer row">
          <form class="col-6" action="{% url 'restaurant:allowing' pre_admin_table %}" method="POST">{% csrf_token %}
            <button type="submit" class="w-100 btn btn__blue" onclick="loading_show(); style.display='none';">
              許可
            </button>
          </form>
          <form class="col-3 text-right" action="{% url 'restaurant:deny' pre_admin_table %}" method="POST">{% csrf_token %}
            <button type="submit" class="btn btn__grey" onclick="loading_show(); style.display='none';">
              拒否
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endif %}

templates/components/restaurant/modal/category.html
{% if user.is_authenticated %}
  <button type="button" class="category-manage-btn btn btn__blue shadow px-3" data-toggle="modal" data-target="#category-manage-btn__ModalCenter">
    <i class="fas fa-pencil-alt"></i>
  </button>

  <div class="modal modal-category fade" id="category-manage-btn__ModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header row">
          <h5 class="modal-title col-10" id="exampleModalCenterTitle">
            カテゴリ* を追加<br />
            <span class="pl-3 text__small">*メニューのまとまりのことです。<br />例)「メイン」「一品物」「飲み物」「飲み放題」</span>
          </h5>
          <button type="button" class="col-2 close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-wrap">
            {% for category in categories %}
              <p class="category-item p-2 mr-1">{{ category.name }}</p>
            {% endfor %}
          </div>
          <hr class="pb-3">

          <form class="py-2" action="{% url 'restaurant:category_add' %}" method="POST">{% csrf_token %}
            <div class="pb-4">
              <input name="add_category_form" type="text" required><br />
              <input class="mt-3" name="nomiho" type="checkbox" value="True">飲み放題用
            </div>
            <button type="submit" class="mt-2 w-50 btn btn__orange" onclick="loading_show(); style.display='none';">
              保存
            </button>
          </form>
        </div>
      </div>

      <div class="modal-content my-5">
        <div class="modal-header row">
          <h5 class="modal-title col-10" id="exampleModalCenterTitle">
            カテゴリの名前/タイプを変更
          </h5>
          <button type="button" class="col-2 close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form class="py-2" action="{% url 'restaurant:category_ch' %}" method="POST">{% csrf_token %}
            <div class="pb-3 d-flex justify-content-around">
              <div>
                <p class="mb-1">変更前の名前</p>
                <select name="category_name" class="py-2 mb-4">
                  {% for category in categories %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                  {% endfor %}
                </select>
              </div>
              <div>
                <p class="mb-1">変更後の名前</p>
                <input type="text" name="ch_category_form" required><br />
              </div>
            </div>
            <div class="mb-4">
              <input name="nomiho" type="checkbox" value="True">飲み放題用
            </div>
            <button type="submit" class="mt-2 w-50 btn btn__light-orange">
              更新
            </button>
          </form>
        </div>
      </div>

      <div class="modal-content mb-5">
        <div class="modal-header row">
          <h5 class="modal-title col-10" id="exampleModalCenterTitle">
            カテゴリを削除
          </h5>
          <button type="button" class="col-2 close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form class="py-2" action="{% url 'restaurant:category_del' %}" method="POST">{% csrf_token %}
            <div class="py-2 mt-3 mb-4">
              <select name="del_category_form" class="py-2">
                {% for category in categories %}
                  <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
              </select>
            </div>
            <button type="submit" class="mt-2 w-50 btn btn__grey" onclick="loading_show(); style.display='none';">
              実行
            </button>
          </form>
        </div>
      </div>

      <div class="modal-content">
        <div class="modal-header row">
          <h5 class="modal-title col-10" id="exampleModalCenterTitle">
            メニューの属するカテゴリを変更
          </h5>
          <button type="button" class="col-2 close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form class="py-2" action="{% url 'restaurant:category_menu_ch' %}" method="POST">{% csrf_token %}
            <div class="py-2 d-flex align-items-center justify-content-around">
              <div class="py-3">
                <label>カテゴリー</label>
                <select name="category_id" class="w-100 my-3 py-2">
                  {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="py-3">
                <label>メニュー</label>
                <select name="menu_id" class="w-100 my-3 py-2">
                  {% for menu in menus %}
                    <option value="{{ menu.id }}">{{ menu.name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <button type="submit" class="w-50 btn btn__blue" onclick="loading_show(); style.display='none';">
              更新
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endif %}

templates/components/restaurant/modal/chef.html
{% if user.is_authenticated %}
<button type="button" class="chef-btn btn btn__blue shadow px-3" data-toggle="modal" data-target="#chef-btn__ModalCenter">
  <i class="fas fa-pencil-alt"></i>
</button>

<div class="modal modal-chef fade" id="chef-btn__ModalCenter" tabindex="-1" role="dialog" aria-labelledby="chef-btn__ModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <form class="modal-content" enctype="multipart/form-data" action="{% url 'restaurant:chef' menu.id %}" method="POST">{% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="menu-chef-img-manage-btn__ModalCenterTitle">
          シェフの顔写真・コメントを更新する
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <label>写真</label><br>
          <input class="text-center" type="file" name="chef_img" value="{{ menu.name }}">
        </div>
        <div class="py-3 comment-edit">
          <label>コメント</label><br>
          <textarea class="w-100 pl-2 shadow" type="text" name="comment" value="{{ menu.comment }}">{% if menu.comment %}{{ menu.comment }}{% endif %}</textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="px-4 py-2 btn btn__grey" data-dismiss="modal">中止</button>
        <button type="submit" class="px-4 py-2 btn btn__blue w-50 mx-auto" onclick="loading_show(); style.display='none';">
          更新
        </button>
      </div>
    </form>
  </div>
</div>
{% endif %}