Beanstalk/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

api/urls.py
from rest_framework import routers
from .views import UserViewSet, NonLoginUserViewSet, CartUserViewSet, OrderViewSet, CategoryViewSet, AllergyViewSet, MenuViewSet


router = routers.DefaultRouter()
router.register(r'user', UserViewSet)
router.register(r'non_login_user', NonLoginUserViewSet)
router.register(r'cart', CartUserViewSet)
router.register(r'order', OrderViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'allergy', AllergyViewSet)
router.register(r'menu', MenuViewSet)

beanstalk/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gaestd_py_django_local_static]
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include
from api.urls import router as api_router
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('customer.urls')),
    path('', include('restaurant.urls')),
    url(r'^api/', include(api_router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# [END gaestd_py_django_local_static]

customer/urls.py
from django.urls import path
from . import views


app_name = 'customer'
urlpatterns = [
    path('', views.index, name='index'),
    path('table/', views.table, name='table'),
    path('waiting/', views.waiting, name='waiting'),
    path('waiting/admin/', views.waiting_admin, name='waiting_admin'),
    path('judge/', views.judge, name='judge'),
    path('allowing/', views.allowing, name='allowing'),
    path('deny/', views.deny, name='deny'),
    path('denied/', views.denied, name='denied'),
    path('menu/', views.menu, name='menu'),
    path('<int:category_id>/filter/', views.filter, name='filter'),
    path('<int:menu_id>/detail/', views.menu_detail, name='menu_detail'),
    # path('<int:menu_id>/detail/request/', views.request, name='request'),
    # path('<int:menu_id>/detail/request/delete/', views.request_del, name='request_del'),
    # path('<int:cart_id>/detail/cart/request/', views.request_cart, name='request_cart'),
    # path('<int:cart_id>/detail/cart/request/delete/', views.request_cart_del, name='request_cart_del'),
    path('cart/<int:menu_id>/', views.cart, name='cart'),
    path('cart/static/', views.cart_static, name='cart_static'),
    path('cart/<int:menu_id>/detail/', views.cart_detail, name='cart_detail'),
    path('cart/<int:cart_id>/cart_ch/', views.cart_ch, name='cart_ch'),
    path('order/', views.order, name='order'),
    path('nomiho/<int:nomiho_id>', views.nomiho, name='nomiho'),
    path('history/', views.history, name='history'),
    path('thanks/', views.thanks, name='thanks'),
    path('stop/', views.stop, name='stop'),
]

restaurant/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'restaurant'
urlpatterns = [
    path('login/', views.login_as_user, name='login'),
    # path('confirm/', views.confirm, name='confirm'),
    path('send/', views.send_code, name='send_code'),
    path('order_manage/', views.order_manage, name='order_manage'),
    path('order_manage/<int:order_id>/change/', views.order_status_ch, name='order_status_ch'),
    path('order_manage/<int:order_id>/change/menu/', views.order_status_ch_menu, name='order_status_ch_menu'),
    path('order_manage/history/', views.history, name='history'),
    path('order_manage/history/total/', views.total, name='total'),
    path('order_manage/history/total/<int:pre_admin_table>/allowing/', views.allowing, name='allowing'),
    path('order_manage/history/total/<int:pre_admin_table>/deny/', views.deny, name='deny'),
    path('order_manage/history/total/<int:active_table>/stop/', views.stop_user_order, name='stop_user_order'),
    path('order_manage/history/total/<int:active_table>/price/change/', views.price_ch, name='price_ch'),
    path('order_manage/history/daily/', views.daily, name='daily'),
    path('manage/login/', views.manage_login, name='manage_login'),
    path('manage/company/logo', views.company_logo, name='company_logo'),
    path('manage/company/name', views.company_name, name='company_name'),
    path('manage/menu/', views.manage_menu, name='manage_menu'),
    path('manage/menu/add', views.category_add, name='category_add'),
    path('manage/menu/change', views.category_ch, name='category_ch'),
    path('manage/menu/delete', views.category_del, name='category_del'),
    path('manage/menu/category/change', views.category_menu_ch, name='category_menu_ch'),
    path('manage/menu/menu/add', views.menu_add, name='menu_add'),
    path('manage/menu/menu/<int:menu_id>/delete', views.menu_del, name='menu_del'),
    path('manage/menu/menu/<int:menu_id>/img', views.menu_img_manage, name='menu_img_manage'),
    path('manage/menu/menu/<int:menu_id>/name', views.menu_name_manage, name='menu_name_manage'),
    path('manage/menu/menu/<int:menu_id>/price', views.menu_price_manage, name='menu_price_manage'),
    path('manage/menu/menu/<int:menu_id>/allergy/change', views.allergy_ch, name='allergy_ch'),
    path('manage/menu/allergy/item/add', views.allergy_add, name='allergy_add'),
    path('manage/menu/allergy/item/delete',
         views.allergy_del, name='allergy_del'),
    path('manage/menu/menu/<int:menu_id>/chef/', views.chef, name='chef'),
    path('manage/menu/nomiho/add', views.nomiho_add, name='nomiho_add'),
    path('manage/menu/nomiho/change', views.nomiho_ch, name='nomiho_ch'),
    path('manage/menu/nomiho/delete', views.nomiho_del, name='nomiho_del'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

restaurant/views.py
import datetime
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.db.models import Q
from itertools import chain
from django.template import Context, Template
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib
import datetime
from itertools import groupby
from .models import Category, Allergy, Menu, Nomiho
from account.models import Table, User, nonLoginUser
import customer.models
from beanstalk.settings import (
    CODE,
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    EMAIL_HOST,
    EMAIL_PORT
)


# Create your views here.
def login_as_user(request):
    user = User.objects.get(id=1)
    try:
        user = User.objects.get(id=2)
    except Exception:
        pass
    try:
        user = User.objects.get(id=3)
    except Exception:
        pass

    email = user.email
    ctx = {
        'email': email
    }

    return render(request, 'restaurant/login.html', ctx)


# @require_POST
# def confirm(request):
    # categories = Category.objects.defer('created_at').order_by('id')
    # try:
    #     first_category = categories[0]
    #     menus = Menu.objects.defer('created_at').filter(
    #         category=first_category).order_by('-id')
    # except:
    #     menus = None
    # allergies = Allergy.objects.all().order_by('id')
    # ctx = {
    #     'categories': categories,
    #     'menus': menus,
    #     'allergies': allergies,
    # }

#     # メールアドレスを取得
#     email = request.POST.get('username')

#     # セッションにすでにユーザがいれば削除
#     if 'user' in request.session:
#         del request.session['user']

#     # ランダムな4桁の文字列を生成
#     passcode = str(random.randrange(10)) + str(random.randrange(10)) + str(random.randrange(10)) + \
#         str(random.randrange(10))

#     # メールアドレスとパスコードのセットになったセッションを作成
#     request.session['user'] = {email: passcode}

#     # パスコードをメール送信
#     EMAIL = EMAIL_HOST_USER
#     PASSWORD = EMAIL_HOST_PASSWORD
#     TO = email

#     msg = MIMEMultipart('alternative')
#     msg['Subject'] = '【注文・メニュー管理システム】4ケタの数字をログイン画面に入力してください'
#     msg['From'] = EMAIL
#     msg['To'] = TO

#     html = """\
#     <html>
#       <head>
#       </head>
#       <body>
#         <p>{{ passcode }}</p>
#       </body>
#     </html>
#     """

#     html = Template(html)
#     context = Context({'passcode': passcode})
#     template = MIMEText(html.render(context=context), 'html')
#     msg.attach(template)

#     try:
#         s = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
#         s.starttls()
#         s.login(EMAIL, PASSWORD)
#         s.sendmail(EMAIL, TO, msg.as_string())
#         s.quit()
#         messages.info(
#             request, f"入力したメールアドレス宛てに4ケタの数字が書かれたメールを送信しました。その数字を以下に入力してください。")
#     except Exception:
#         messages.error(request, f"メール送信に失敗しました。お手数ですがメールアドレスの入力からやり直してください。")
#         return redirect('restaurant:login')

#     ctx['email'] = email

#     return render(request, 'restaurant/confirm.html', ctx)


def send_code(request):
    # メールアドレスを取得
    email = request.POST.get('username')
    code = CODE

    if email == None:
        messages.info(request, f"送信対象となるメールアドレスが登録されていません。")
        return redirect('restaurant:login')

    EMAIL = EMAIL_HOST_USER
    PASSWORD = EMAIL_HOST_PASSWORD
    TO = email

    msg = MIMEMultipart('alternative')
    msg['Subject'] = '【注文・メニュー管理システム】4ケタの暗証番号をお送りします'
    msg['From'] = EMAIL
    msg['To'] = TO

    html = """\
    <html>
      <head>
      </head>
      <body>
        <p>{{ code }}</p>
      </body>
    </html>
    """

    html = Template(html)
    context = Context({'code': code})
    template = MIMEText(html.render(context=context), 'html')
    msg.attach(template)

    try:
        s = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
        s.starttls()
        s.login(EMAIL, PASSWORD)
        s.sendmail(EMAIL, TO, msg.as_string())
        s.quit()
        messages.info(
            request, f"メールアドレス宛てに4桁の暗証番号が書かれたメールを送信しました。その数字を入力してください。")
        return redirect('restaurant:login')
    except Exception:
        messages.error(request, f"メール送信に失敗しました。お手数ですがメールアドレスが有効か、ご確認ください。")
        return redirect('restaurant:login')


def order_manage(request):
    try:
        filter_type = request.POST.get('filter-type')
    except Exception:
        filter_type = None

    # ログインから
    if request.method == 'POST' and filter_type == 'login':
        email = request.POST.get('username')
        # passcode = request.POST.get('passcode')

        # 入力されたパスコードがセッションに保持されたパスコードと一致するならログインを許可
        # if passcode == request.session['user'][email]:
        try:
            user = User.objects.get(email=email)
            code = request.POST.get('code')

            if code == CODE:
                login(request, user)
                request.session['table'] = '管理者'
            else:
                messages.info(request, f"暗証番号が異なります。")
                return redirect('restaurant:login')

        except Exception:
            messages.info(request, f"メールアドレスが異なります。")
            return redirect('restaurant:login')

        # emailのセッションを作成(いきなりオーダー画面にアクセスするお店を識別する為)
        email = user.email
        request.session['user_email'] = email

        return render(request, 'restaurant/order_manage.html')

    # いきなりこの画面から＆メニュー編集画面から戻ってくるパターン(多くの店がこの想定)
    elif 'user_email' in request.session:
        user_email = request.session['user_email']
        user = User.objects.get(email=user_email)
    else:
        user = User.objects.get(id=1)
        try:
            user = User.objects.get(id=2)
        except Exception:
            pass
        try:
            user = User.objects.get(id=3)
        except Exception:
            pass

    formatted_logo = user.formatted_logo
    name = user.name
    order_list = ''
    table = None

    active_users = nonLoginUser.objects.defer('created_at').filter(active=True)
    menus = Menu.objects.defer('created_at').order_by('id')

    # テーブル番号でフィルタした際
    if request.POST.get('table') != None:
        table = request.POST.get('table')
        active_users = nonLoginUser.objects.defer(
            'created_at').filter(table=table, active=True)

    for active_user in active_users:
        active_user_order = customer.models.Order.objects.filter(
            customer=active_user, status='調理中', curr=True).order_by('-id')
        order_list = list(chain(order_list, active_user_order))

    ctx = {
        'formatted_logo': formatted_logo,
        'name': name,
        'table': table,
        'order_list': order_list,
        'menus': menus,
    }

    return render(request, 'restaurant/order_manage.html', ctx)


@login_required
@require_POST
def order_status_ch(request, order_id):
    order_status = request.POST.get('order_status')
    order = customer.models.Order.objects.get(id=order_id)
    order.status = order_status
    order.save()

    # テーブルの合計も変更する
    if order_status == 'キャンセル':
        table_num = order.customer.table
        table = Table.objects.get(table=table_num, active=True)
        table.price -= int(order.menu.price) * int(order.num)
        table.save()

    return redirect('restaurant:order_manage')


@login_required
@require_POST
def order_status_ch_menu(request, order_id):
    required_menu_id = request.POST.get('required_menu_id')
    required_order_num = request.POST.get('required_order_num')
    menu = Menu.objects.get(id=required_menu_id)
    order = customer.models.Order.objects.get(id=order_id)

    curr_menu = order.menu
    curr_num = order.num

    order.menu = menu
    order.num = required_order_num
    order.save()

    # テーブルの合計も変更する
    table_num = order.customer.table
    table = Table.objects.get(table=table_num, active=True)
    table.price -= int(curr_menu.price) * int(curr_num)
    table.price += int(menu.price) * int(required_order_num)
    table.save()

    return redirect('restaurant:order_manage')


@login_required
def history(request):
    user = User.objects.get(id=request.user.id)
    name = user.name
    active_users = nonLoginUser.objects.defer('created_at').filter(active=True)
    menus = Menu.objects.defer('created_at').order_by('id')
    order_list = ''
    start = None
    end = None
    table = None

    # 日付の範囲指定分の売上
    if request.method == 'POST':
        filter_type = request.POST.get('filter-type')
        start = request.POST.get('start')
        end = request.POST.get('end')
        table = request.POST.get('table')

        if (start != None) and (end != None):
            request.session['filter_date_start'] = start
            request.session['filter_date_end'] = end

            if 'filter_table' in request.session:
                table = request.session['filter_table']
                same_table_users = nonLoginUser.objects.defer(
                    'created_at').filter(table=table, active=True)
            else:
                same_table_users = active_users

            if start > end:
                messages.warning(request, f"左の日付をより昔にしてください。")
                (start, end) = (end, start)

            for same_table_user in same_table_users:
                active_user_order = customer.models.Order.objects.filter(
                    customer=same_table_user, created_at__range=(start, end)).order_by('-id')
                order_list = list(chain(order_list, active_user_order))

        elif filter_type == 'date-filter-clear':
            request.session['filter_date_start'] = None
            request.session['filter_date_end'] = None

            if 'filter_table' in request.session:
                table = request.session['filter_table']
                active_users = nonLoginUser.objects.defer(
                    'created_at').filter(table=table, active=True)

            for active_user in active_users:

templates/restaurant/daily.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block custom__header %}
  <title>売上管理</title>
{% endblock %}

{% block content %}
<div class="w-100 restaurant">
  {% include 'components/restaurant/header.html' %}
  <section class="pt-5 daily">
    <div class="p-sm-5 pt-5 p-2">
      <div class="daily-interest shadow p-sm-3 p-2 m-2">
        <p>指定期間内の売上と各商品の数量</p>
        <div class="py-3">
          <p class="text-center text__bold text__large">{{ pointed_total_price }}　円</p>
          <form action="{% url 'restaurant:daily' %}" method="POST">{% csrf_token %}
            <p class="pb-2">期間を指定してください</p>
            <div class="d-sm-flex align-items-center">
              <div class="d-flex align-items-center">
                <input type="datetime-local" name="start" value="{{ start }}" required on>
                <p class="px-2">から</p>
              </div>
              <div class="d-flex align-items-center py-sm-0 py-2">
                <input type="datetime-local" name="end" value="{{ end }}" required on>
                <p class="px-2">まで</p>
                <button type="submit" class="ml-sm-3 ml-4 btn btn__blue px-3">
                  絞り込み
                </button>
              </div>
            </div>
          </form>
        </div>

        <div class="row">
          <div class="col-sm-6 col-12">
            <p>テーブル毎単品詳細（飲み放題メニュー抜き）</p>
            <table border="1" class="w-100">
              <tr class="text-center">
                <th>料理名</th>
                <th>単価（円）</th>
                <th>個数</th>
              </tr>
              {% for order in pointed_orders %}
                {% if not order.menu.price == 0 %}
                  <tr>
                    <td class="px-sm-3 px-2">{{ order.menu.name }}</td>
                      <td class="px-sm-3 px-2 text-right">{{ order.menu.price | intcomma }}</td>
                    <td class="px-sm-3 px-2 text-right">{{ order.num }}</td>
                  </tr>
                {% endif %}
              {% endfor %}
            </table>
          </div>
          <div class="col-sm-6 col-12">
            <p>飲み放題</p>
            <table border="1" class="w-100">
              <tr class="text-center">
                <th>プラン名</th>
                <th>単価（円）</th>
                <th>人数</th>
              </tr>
              {% for pointed_nomiho_order in pointed_nomiho_orders %}
                <tr>
                  <td class="px-sm-3 px-2">{{ pointed_nomiho_order.nomiho.name }}</td>
                  <td class="px-sm-3 px-2 text-right">{{ pointed_nomiho_order.nomiho.price }}</td>
                  <td class="px-sm-3 px-2 text-right">{{ pointed_nomiho_order.num }}</td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>

        <!-- <div class="text-right mt-5">
          <p>割引した額:{{ discount_pointed_price }} 円</p>
        </div> -->

      </div>

      <div class="total-interest shadow p-sm-3 p-2 mt-5 m-2">
        <p>売上総額</p>
        <div class="py-3">
          <p class="text-center text__bold text__large">{{ total_price }}　円</p>
        </div>
        <div class="row">
          <div class="col-sm-6 col-12">
            <p>テーブル毎単品詳細（飲み放題メニュー抜き）</p>
            <table border="1" class="w-100">
              <tr class="text-center">
                <th>料理名</th>
                <th>単価（円）</th>
                <th>個数</th>
              </tr>
              {% for order in orders %}
                {% if not order.menu.price == 0 %}
                  <tr>
                    <td class="px-sm-3 px-2">{{ order.menu.name }}</td>
                    <td class="px-sm-3 px-2 text-right">{{ order.menu.price }}</td>
                    <td class="px-sm-3 px-2 text-right">{{ order.num }}</td>
                  </tr>
                {% endif %}
              {% endfor %}
            </table>
          </div>

          <div class="col-sm-6 col-12">
            <p>飲み放題</p>
            <table border="1" class="w-100">
              <tr class="text-center">
                <th>料理名</th>
                <th>単価（円）</th>
                <th>個数</th>
              </tr>
              {% for nomiho_order in nomiho_orders %}
                <tr>
                  <td class="px-sm-3 px-2">{{ nomiho_order.nomiho.name }}</td>
                  <td class="px-sm-3 px-2 text-right">{{ nomiho_order.nomiho.price }}</td>
                  <td class="px-sm-3 px-2 text-right">{{ nomiho_order.num }}</td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>

        <!-- <div class="text-right mt-5">
          <p>割引した額:{{ discount_price }} 円</p>
        </div> -->
      </div>
    </div>
  </section>
</div>
{% endblock %}

templates/restaurant/history.html
{% extends 'base.html' %}
{% load static %}

{% block custom__header %}
  <title>修正</title>
{% endblock %}

{% block content %}
<div class="w-100 restaurant">
  {% include 'components/restaurant/header.html' %}
  <div class="pt-5">
    <div class="pt-sm-3 pt-5">

      <div class="d-sm-flex align-items-center">
        <div class="pt-sm-5 mx-3 d-sm-flex align-items-center">
          <form action="{% url 'restaurant:history' %}" method="POST">{% csrf_token %}
            <p class="pb-2">期間を指定してください</p>
            <div class="d-sm-flex align-items-center">
              <div class="d-flex align-items-center">
                <input type="datetime-local" name="start" value="{{ request.session.filter_date_start }}" required>
                <p class="px-2">から</p>
              </div>
              <div class="d-flex align-items-center py-sm-0 py-2">
                <input type="datetime-local" name="end" value="{{ request.session.filter_date_end }}" required>
                <p class="px-2">まで</p>
                <button type="submit" class="ml-sm-3 ml-5 btn btn__blue px-3 text__small">
                  絞り込み
                </button>
              </div>
            </div>
          </form>

          <form class="pt-1 ml-2 mr-sm-0 mr-4 text-right" action="{% url 'restaurant:history' %}" method="POST">{% csrf_token %}
            <!-- hidden -->
            <input type="hidden" name="filter-type" value="date-filter-clear">
            <button type="submit" class="btn btn__grey mt-sm-4 text__small">
              クリア
            </button>
          </form>
        </div>

        <div class="pt-sm-5 pt-3 mx-3 d-sm-flex align-items-center">
          <form action="{% url 'restaurant:history' %}" method="POST">{% csrf_token %}
            <p class="pb-2">テーブル番号を指定してください</p>
            <div class="d-sm-flex align-items-center py-sm-0 py-2">
              <input type="number" name="table" class="mr-2 text-center text__bold text__large" min="1"
                {% if request.session.filter_table %}
                  value="{{ request.session.filter_table }}"
                {% else %}
                  value="{{ table }}"
                {% endif %}
                required>番
              <button type="submit" class="ml-sm-3 ml-5 btn btn__blue px-3 text__small">
                絞り込み
              </button>
            </div>
          </form>

          <form class="pt-1 ml-2 mr-sm-0 mr-4 text-right" action="{% url 'restaurant:history' %}" method="POST">{% csrf_token %}
            <!-- hidden -->
            <input type="hidden" name="filter-type" value="table-filter-clear">
            <button type="submit" class="btn btn__grey mt-sm-4 text__small">
              クリア
            </button>
          </form>
        </div>
      </div>

      {% include 'components/restaurant/order_table.html' %}
    </div>
  </div>
</div>
{% endblock %}

templates/restaurant/login.html
{% extends 'base.html' %}
{% load static %}

{% block custom__header %}
  <title>注文管理</title>
{% endblock %}

{% block content %}
<div class="wrapper restaurant w-100">
  <div class="inner__wrapper m-auto py-5 px-sm-0 px-3">
    <div class="board shadow beautify text-center my-5 py-4 px-5">
      <h4 class="text__bold">
        {% if request.path == '/login/' %}
          ログイン画面
        {% elif request.path == '/manage/login/' %}
          メニュー管理
        {% endif %}
      </h4>
      <div class="d-flex p-5 mx-sm-5">
        <div class="pl-5">
          <img src="{% static 'img/logo.png' %}" alt="Logo" class="logo shadow">
        </div>
        <h5 class="m-auto">注文・メニュー管理</h5>
      </div>
      <form method="POST" action="{% url 'restaurant:order_manage' %}">{% csrf_token %}
        <div>
          <label>メールアドレス</label><br>
          {% if email %}
            <input name="username" value="{{ email }}" class="px-3 mb-3 w-sm-50 w-100 py-2 text__bold text__large" readonly>
          {% else %}
            <input name="username" class="px-3 mb-3 w-sm-50 w-100 py-2 text__bold text__large">
          {% endif %}
          <br>
        </div>
        <div>
          <label>4桁の暗証番号</label><br>
          {% if request.session.code %}
            <input class="text-center text__bold text__large" type="text" name="code" value="{{request.session.code}}" required>
          {% else %}
            <input class="text-center text__bold text__large" type="text" name="code" required>
          {% endif %}
          <br>
        </div>
        <div class="pt-5">
          <!-- hidden -->
          <input type="hidden" name="filter-type" value="login">
          <button type="submit" class="px-5 py-3 btn btn__blue shadow" id="loginBtn">
            ログイン
          </button>
        </div>
      </form>

      <form class="pt-5 pb-3 d-sm-flex justify-content-center align-items-center mt-sm-0 mt-5" action="{% url 'restaurant:send_code' %}" method="POST" onclick="loading_show(); style.display='none';">{% csrf_token %}
        <!-- hidden -->
        {% if email %}
          <input type="hidden" name="username" value="{{ email }}">
        {% else %}
          <input type="hidden" name="username">
        {% endif %}
        <button type="submit" class="shadow btn btn__grey text__small">
          暗証番号をメールで確認する
        </button>
      </form>
    </div>

    <div class="pt-3 admin row">
      <div class="col-sm-6 col-12">
        {% if request.path == '/manage/login/' %}
          <a href="{% url 'restaurant:order_manage' %}" onclick="loading_show()">注文管理画面に戻る</a>
        {% endif %}
      </div>
      <div class="col-sm-6 col-12 text-sm-right pt-sm-0 pt-3">
        <a href="{% url 'customer:index' %}" onclick="loading_show()">お客様から見える画面を確認する</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/restaurant/order_table.html
<section class="px-3 py-3 order-table">
  <div class="d-flex justify-content-between mb-2">
    <div class="d-flex ml-2">
      <p class="mr-sm-5 mr-3">ステータス▼</p>
      <p>テーブル番号▼</p>
    </div>
    <div class="d-flex mr-5">
      <p class="mr-sm-5 mr-3">個数</p>
      <p>注文時間</p>
    </div>
  </div>

  <!-- vue_draggable -->
  <div id="order_manage">
    <draggable :list="items">
      {% for order in order_list %}
        <div v-for="item in items" class="order-item el__pointer shadow py-4 my-2">
          {% block order_modal %}
            {% include 'restaurant/order_modal.html' %}
          {% endblock %}
        </div>
      {% endfor %}
    </draggable>
      <!-- TODO: -->
      <!-- items: [[ items ]] -->
  </div>
</section>